version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login $HARBOR_URL  -u $HARBOR_DOCKER_USERNAME -p $HARBOR_DOCKER_PASSWORD
      - run:
          name: "Build docker image and push to docker hub"
          command: |
            docker build -t harbor.touch-ics.com/library/gobuild:latest .
            docker image ls .
            docker push harbor.touch-ics.com/library/gobuild:latest
      - run: echo Done
